name: DPLL-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        mkdir build
        cmake -B build -DCMAKE_BUILD_TYPE=release
        make -C build
      env:
        CI: true

    - name: Verifying
      run: |
        sudo apt install picosat
        python3 test.py
      env:
        CI: true

